trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Hello World!"
  displayName: 'First script'

- script: |
    echo "Add other tasks..."
    echo "Like this one..."
  displayName: 'Second Script'
